export const ADMIN_ROUTE='/admin'
export const LOGIN_ROUTE='/login'
export const REGISTER_ROUTE='/register'
export const BASKET_ROUTE='/basket'
export const SHOP_ROUTE='/'
export const DEVICE_ROUTE='/device'